#!/bin/bash

command=$1
shift

DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

>&2 echo "AR: $(${DIR}/config.py BINUTILS_BUILD_DIR)/binutils/ar ${command} --plugin $(${DIR}/config.py GOLD_PLUGIN) $*"

"$(${DIR}/config.py BINUTILS_BUILD_DIR)/binutils/ar" ${command} --plugin "$(${DIR}/config.py GOLD_PLUGIN)" $*

#>&2 echo "AR: $(${DIR}/config.py BINUTILS_BUILD_DIR)/binutils/ar ${command}s --plugin $(${DIR}/config.py GOLD_PLUGIN) $*"

#"$(${DIR}/config.py BINUTILS_BUILD_DIR)/binutils/ar" ${command}s --plugin "$(${DIR}/config.py GOLD_PLUGIN)" $*

#for arg in $*; do
  #echo $arg | grep '^.*\.a$' > /dev/null
  #if [[ $? -eq 0 ]] ; then
    #target=$arg
  #fi
#done

#>&2 echo "RANLIB $(${DIR}/config.py BINUTILS_BUILD_DIR)/binutils/ranlib --plugin $(${DIR}/config.py GOLD_PLUGIN) $target"
#"$(${DIR}/config.py BINUTILS_BUILD_DIR)/binutils/ranlib" --plugin "$(${DIR}/config.py GOLD_PLUGIN)" $target
