#!/bin/bash

command=$1
shift

DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)

>&2 echo "AR: $(${DIR}/config.py BINUTILS_BUILD_DIR)/binutils/ar $command --plugin $(${DIR}/config.py GOLD_PLUGIN) $*"

"$(${DIR}/config.py BINUTILS_BUILD_DIR)/binutils/ar" $command --plugin "$(${DIR}/config.py GOLD_PLUGIN)" $*

